### ISSUE TITLE
Hamlib4

### ISSUE THREAD

**Issue by df8oe** [fillods/grig#1]
Hi,
this version is incompatible with hamlib4. There are already some suggestions here: https://sourceforge.net/p/groundstation/discussion/80394/thread/214ff5bfa6/ It would be great if grig can be updated to work with hamlib4 :)

**Comment by mdblack98** [comment]
I fixed it for Hamlib4 -- for some reason seems I can't fork the repository and do a pull request.
I just called this 0.8.2
https://www.dropbox.com/s/stxbn22sj45ssor/grig-0.8.2.tar.gz?dl=0

**Comment by mattmelling** [comment]
@mdblack Are these changes made against 0.8.1 or the current head of this repo - 0.9.0~git?

**Comment by mdblack98** [comment]
It was against 0.8.1
I just forked it and it was a much smaller change to the current master -- just two lines so it's a pull request now.

https://github.com/fillods/grig/pull/6/commits/ec877a5cd0adfaee8439f9dde04b425e6f48c6de

**Comment by fillods** [comment]
Merged.
Thanks Mike !
