### ISSUE TITLE
Replacement for deprecated declarations of Glib

### ISSUE THREAD

**Issue by fillods** [fillods/grig#11]
A replacement is needed for the deprecated declarations of Glib, easily identified by compile warnings:

```
src/grig-debug.c:250:9: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
src/grig-debug.c:254:9: warning: ‘g_get_current_time’ is deprecated: Use 'g_get_real_time' instead [-Wdeprecated-declarations]
...
```

**Comment by mattmelling** [comment]
Fixed this in my fork over the holidays, have spun out to PR #12

**Comment by fillods** [comment]
@mattmelling you're right, the other declarations came from gtktooltips rather than our code.
