### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by mattmelling** [fillods/grig#5]
In commit https://github.com/fillods/grig/commit/6457b0f648796f0025936e0d8133f82a1b9b3a1a the version was bumped to 0.9.0~git. This version does not show up in the git tags or as a version on sourceforge.

Is this an 'official' release? If not is there a plan for a new release?

Debian testing is using version 0.8.1. Arch has both 0.8.1 and git-tracking packagers in the AUR.

I am packaging for NixOS and looking for a milestone version we can use for reproducible builds, the newer the better.

**Comment by fillods** [comment]
Yes, there's a plan for a new release soon.
I've merged and pushed some fixes. Please beta-test the repo before I make an official release (0.9.0).

**Comment by mattmelling** [comment]
Great news.

I have been testing the hamlib 4 changes merged yesterday which all look good so far - although have not put it through any rigorous shack usage yet.

**Comment by df7cb** [comment]
Debian would also like to see a git tag to pull the tarball from. Thanks!

**Comment by fillods** [comment]
Will do!   (same as with previous releases : `GRIG-x_y_z`)

**Comment by fillods** [comment]
Grig 0.9.0 released.

**Comment by df7cb** [comment]
Debian package updated, thanks!
