### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by dforsi** [fillods/grig#9]
Hello,

I would like to start the Italian translation, if nobody is working on it.
I would use poedit and open a pull request here in a couple of days.

**Comment by ew1abz** [comment]
Awesome! Thank you!

**Comment by fillods** [comment]
FYI, the template file `po/grig.pot` has been updated today.

**Comment by dforsi** [comment]
I found two small issues:

1. this tooltip of the "A = B" button seems wrong:
"Set VFO B = VFO A"
I think that it should be
"Set VFO A = VFO B"
2. the column "Version" of the list heading could be made larger because the version strings are 10 characters long:
```
   ID  Manufacturer     Model                  Ver.   Status
---------------------------------------------------------------
    1  Hamlib           Dummy                  20220727.0 Stable
    2  Hamlib           NET rigctl             20220722.0 Stable
...
```
something like this:
```
   ID  Manufacturer     Model                  Version    Status
----------------------------------------------------------------
    1  Hamlib           Dummy                  20220727.0 Stable
    2  Hamlib           NET rigctl             20220722.0 Stable
...
```

What do you think?

**Comment by fillods** [comment]
1. You may change the tooltip of "A = B" as you suggested, but anyhow this is not really an operation to "Set VFO A = VFO B". The RIG_OP_CPY actually set the undisplayed VFO frequency and mode to those of the displayed VFO...
2. Go ahead with a larger column "Version" of the list heading 

Thanks for taking the time to refine Grig.
